/**
 * Save Discovery Tool
 *
 * Saves an interesting discovery from curiosity mode.
 * Can save as new IP, new lesson, or personal notes.
 */

import { tool } from "ai";
import { z } from "zod";

export const saveDiscovery = tool({
    description:
        "Save an interesting discovery from the conversation. Use when the user wants to save something they learned or found interesting.",
    inputSchema: z.object({
        title: z.string().describe("Title for the discovery"),
        content: z.string().describe("Content/summary of the discovery"),
        saveAs: z
            .enum(["new_ip", "new_lesson", "notes", "new_course"])
            .describe("How to save the discovery"),
        courseId: z
            .string()
            .optional()
            .describe("Course to add to (for new_ip or new_lesson)"),
        lessonId: z
            .string()
            .optional()
            .describe("Lesson to add to (for new_ip)"),
        tags: z
            .array(z.string())
            .optional()
            .describe("Tags to categorize the discovery"),
    }),
    execute: async ({
        title,
        content,
        saveAs,
        courseId,
        lessonId,
        tags,
    }: {
        title: string;
        content: string;
        saveAs: "new_ip" | "new_lesson" | "notes" | "new_course";
        courseId?: string;
        lessonId?: string;
        tags?: string[];
    }) => {
        // In a full implementation, this would:
        // 1. Validate the save target exists (if courseId/lessonId provided)
        // 2. Create the appropriate entity in the database
        // 3. For new_course, trigger the course creation flow
        // 4. Return the created entity ID

        return {
            success: true,
            title,
            content,
            saveAs,
            courseId,
            lessonId,
            tags,
            // Would be the actual created entity ID
            createdId: "[Would be generated by database]",
            message: `Discovery saved as ${saveAs}`,
            // Signal for UI navigation
            navigateTo:
                saveAs === "new_course"
                    ? "/courses/create"
                    : saveAs === "notes"
                      ? "/notes"
                      : undefined,
        };
    },
});
